name: Run Java Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SQL Server to be ready
        run: sleep 30

      - name: Initialize Database
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Strong@Password1' -Q "CREATE DATABASE master;"
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Strong@Password1' -d master -i initialize.sql

      - name: Run tests
        env:
          DB_URL: "jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false"
          DB_USER: "SA"
          DB_PASSWORD: "Strong@Password1"
        run: |
          mvn test
