name: Run Java Unit Tests

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        env:
          DB_URL: "jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false"
          DB_USER: "temp"
          DB_PASSWORD: "temp1234"
        run: |
          mvn test
